#!/bin/bash
# Quick deployment checklist for Bydex portfolio

echo "🚀 Bydex Portfolio Deployment Checklist"
echo "======================================="
echo ""
echo "✅ COMPLETED:"
echo "  - Portfolio site structure created"
echo "  - Home page with overview"
echo "  - Web development portfolio page"
echo "  - Pottery portfolio page"
echo "  - Navigation and footer components"
echo "  - GitHub Actions workflow configured"
echo "  - CNAME file for custom domain (bydex.co)"
echo "  - Build verified and successful"
echo ""
echo "📋 NEXT STEPS:"
echo ""
echo "1. Push changes to GitHub:"
echo "   git add ."
echo "   git commit -m 'feat: add professional portfolio site'"
echo "   git push -u origin feature-aibuild"
echo ""
echo "2. Create Pull Request on GitHub"
echo "   - Go to github.com/codebydex/bydex-web"
echo "   - Click 'New Pull Request'"
echo "   - Merge feature-aibuild into main"
echo ""
echo "3. Configure GitHub Pages:"
echo "   - Settings → Pages"
echo "   - Source: GitHub Actions"
echo "   - Custom domain: bydex.co"
echo ""
echo "4. Update DNS Records at Domain Registrar:"
echo "   - A records: 185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153"
echo "   - OR CNAME: codebydex.github.io (for subdomain)"
echo ""
echo "5. Verify Deployment:"
echo "   - Wait 5-10 minutes for DNS propagation"
echo "   - Visit https://bydex.co"
echo "   - Check all pages load correctly"
echo ""
echo "📝 Customize Your Content:"
echo "   - Home: app/page.tsx"
echo "   - Web: app/web/page.tsx"
echo "   - Pottery: app/pottery/page.tsx"
echo "   - Navigation: app/components/Navigation.tsx"
echo "   - Footer: app/components/Footer.tsx"
echo ""
echo "💡 Development Commands:"
echo "   npm run dev    # Start local dev server"
echo "   npm run build  # Build for production"
echo "   npm run start  # Start production server"
echo ""
